# Generated by Django 4.2.16 on 2024-10-31 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('unitsvalue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
