# Generated by Django 4.2.16 on 2024-10-31 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unitsvalue', '0002_alter_fund_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livepercentunit',
            name='funds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LivePercentUnit', to='unitsvalue.fund'),
        ),
    ]
